### ISSUE TITLE
Features - Add possibility credentails HTTP auth

### ISSUE THREAD

**Issue by vdeville** [MoonshineSG/Simplify3D-to-OctoPrint#2]
Like Apache .htpasswd

**Comment by MoonshineSG** [comment]
You mean to support upload over the internet ? If you're uploading on your local network, maybe you can skip authentication for local network ? 

Using ".htaccess" something like

```
AuthUserFile /var/www/mysite/.htpasswd
AuthName "Authorised Personnel Only"
AuthType Basic
Require Valid-User
Order Allow, Deny
Allow from 127.0.0.1 192.168.0.0/255.255.0.0
Satisfy Any
```
(or whatever IPs you have locally)
